export const mockTitles = [
  { title: "Learning the BLACKPINK dance in one day", views: 9200 },
  { title: "Can you actually keep up with NewJeans choreo?", views: 15400 },
  { title: "My honest attempt at this dance trend", views: 5100 },
  { title: "Is this the hardest kpop dance ever?", views: 13800 },
  { title: "SEVENTEEN choreography breakdown", views: 10600 },
  { title: "Why does everyone struggle with this move?", views: 12100 },
  { title: "Dance practice, no editing", views: 4300 },
  { title: "Trying BLACKPINK's new title track", views: 11700 },
  { title: "Is this move even humanly possible?", views: 14200 },
  { title: "Simple mirrored dance tutorial", views: 4700 },
  { title: "NewJeans dance but make it harder", views: 10900 },
  { title: "Can beginners really learn this in a week?", views: 13500 },
  { title: "Late night dance session", views: 3900 },
  { title: "SEVENTEEN's fastest choreo yet", views: 11200 },
  { title: "Why is nobody talking about this dance?", views: 12800 },
  { title: "Dance cover, first try", views: 4100 },
  { title: "BLACKPINK dance but 2x speed", views: 12000 },
  { title: "Does this count as cardio?", views: 9800 },
  { title: "Weekend dance practice recap", views: 4500 },
  { title: "NewJeans choreo — how close did I get?", views: 15900 },
];